#!/bin/bash
# Discovery System Setup Guide

echo "🗄️  TasteTrails Discovery System - Database Setup"
echo "=================================================="
echo ""
echo "The discovery system requires these database tables:"
echo "  - discovery_tiles"
echo "  - restaurants (enhanced)"
echo "  - restaurant_aliases"
echo "  - discovery_runs"
echo ""
echo "📋 SETUP INSTRUCTIONS:"
echo ""
echo "Option 1: Supabase Dashboard (Easiest)"
echo "─────────────────────────────────────"
echo "1. Go to: https://supabase.com/dashboard"
echo "2. Select your project"
echo "3. SQL Editor → New Query"
echo "4. Copy-paste the SQL from: sql/discovery_schema.sql"
echo "5. Click ▶️  Execute"
echo ""
echo "Option 2: Supabase CLI"
echo "──────────────────────"
echo "supabase migration new discovery_schema"
echo "# Copy sql/discovery_schema.sql contents to the migration file"
echo "supabase migration up"
echo ""
echo "Option 3: Direct psql (if you have access)"
echo "────────────────────────────────────────"
echo "psql -h <host> -U postgres -d <db> < sql/discovery_schema.sql"
echo ""
echo "❓ After running the SQL:"
echo "  Run this to verify tables exist:"
echo "    SELECT table_name FROM information_schema.tables WHERE table_schema='public';"
echo ""
echo "✅ Once tables are created, run:"
echo "    npm run server"
echo "    # Then:"
echo "    curl -X POST http://localhost:8081/admin/discovery/generate-tiles \\"
echo "      -H 'x-admin-token: dev-token-change-me' \\"
echo "      -H 'Content-Type: application/json' \\"
echo "      -d '{\"city\": \"Charlotte, NC\", \"minLat\": 35.1, \"minLng\": -80.95, \"maxLat\": 35.35, \"maxLng\": -80.7, \"spacingKm\": 3, \"radiusM\": 1500, \"priority\": 5}'"
